// src/tokens.ts
export const tokens = {
  colors: {
    primary: '#BA977B',
    primaryLight: '#FFEDDE',
    primaryVariant: '#8A7353',
    secondary: '#4E7E6A',
    background: '#FFFFFF',
    surface: '#FFFFFF',
    error: '#B00020',
    onPrimary: '#FFFFFF',
    onSecondary: '#000000',
    onBackground: '#000000',
    onSurface: '#000000',
    onError: '#FFFFFF',
    grayLight: '#F5F5F5',
    gray: '#CCCCCC',
    grayMedium: '#595959',
    grayDark: '#666666',
    grayDarker: '#333333',
    black: '#000000',
    white: '#FFFFFF',
  },
  spacing: {
    small: '8px',
    medium: '16px',
    large: '24px',
    extraLarge: '100px',
  },
  typography: {
    fontFamily: '"Inter", sans-serif',
    fontSize: '16px',
    fontWeight: 400,
  },
};
