name: Locize Translation Download and Push

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  my_job:
    runs-on: ubuntu-latest
    name: download and push
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Download translations
        uses: locize/download@v1
        with:
          project-id: ${{ secrets.LOCIZE_PROJECT_ID }}
          api-key: ${{ secrets.LOCIZE_API_KEY }}
          path: /public
      - name: Commit & Push changes
        uses: actions-js/push@master
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
